### ISSUE TITLE
[Bug]: Does not work with eslint v9

### ISSUE THREAD

**Issue by egucciar** [chiefmikey/eslint-plugin-disable-autofix#51]
### What happened?

I wanted to use this package with eslint v9, but it does not support it yet. 

### Version

4.3.0

### Relevant log output

```
Error: This method cannot be used with flat config. Add your entries directly into the config array.
    at assertEslintrcConfig (/Users/erica.gucciardo/observe/code/js/node_modules/eslint/lib/linter/linter.js:1256:15)
    at Linter.getRules (/Users/erica.gucciardo/observe/code/js/node_modules/eslint/lib/linter/linter.js:2185:9)
    at Object.<anonymous> (/Users/erica.gucciardo/observe/code/js/node_modules/eslint-plugin-disable-autofix/index.js:39:29)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by chiefmikey** [comment]
https://github.com/chiefmikey/eslint-plugin-disable-autofix/releases/tag/v5.0.0
